spring:
  application:
    name: spring-store
  datasource:
    url: jdbc:mysql://localhost:3306/store_api?createDatabaseIfNotExist=true
    username: root
    password: Password
  jpa:
    show-sql: true
  jwt:
    secret: xJaJpANIRJyArOBnwSyVe57AO5CYw+kKnxKMKgDZeMdFyh+YrJwnCUegD2NgqtxY