spring:
  application:
    name: spring-store
  datasource:
    url: jdbc:mysql://localhost:3306/store_api?createDatabaseIfNotExist=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:Password}
  jpa:
    show-sql: true
  jwt:
    secret:
    accessTokenExpiration: 15000
    refreshTokenExpiration: 604800
stripe:
  secretKey:
  webhookSecretKey:
websiteUrl: http://localhost/8020/api